# Generated by Django 4.1.1 on 2022-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjCRUD', '0004_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=215)),
                ('address2', models.CharField(blank=True, max_length=215, null=True)),
                ('phonenumber', models.IntegerField(blank=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=215, null=True)),
                ('postel_code', models.CharField(blank=True, max_length=215, null=True)),
            ],
        ),
    ]
