# Generated by Django 4.1.1 on 2022-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjCRUD', '0006_alter_address_postel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postel_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
