# Generated by Django 4.1.1 on 2022-10-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjCRUD', '0008_address_user_alter_address_address1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phonenumber',
            field=models.IntegerField(unique=True),
        ),
    ]
