# Generated by Django 4.1.1 on 2022-10-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjCRUD', '0011_remove_users_confirm_password_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=215, unique=True),
        ),
    ]
