# Generated by Django 4.1.1 on 2022-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjCRUD', '0012_alter_address_address1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default=1, max_length=215),
            preserve_default=False,
        ),
    ]
