# Generated by Django 4.1.1 on 2022-10-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjCRUD', '0014_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
